### ISSUE TITLE
Error: write EPIPE

### ISSUE THREAD

**Issue by Rex1911** [vibhor1997a/compile-run#2]
I get this error in C and C++ when I provide stdin, but in the actual program I never use it.

Eg:
`let resultPromise = c.runSource("#include<stdio.h>int main(){printf("Hello world");return 0;", {stdin: 10\n20});`

The error I get is: 
```
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: write EPIPE
    at exports._errnoException (util.js:1020:11)
    at WriteWrap.afterWrite (net.js:800:14)
```

This just outright **CRASHES** the entire server

This only happens when i provide a stdin and I dont use it in my code.

I've tested this with C,C++ and Python and C and C++ seem to be showing this error while Python doesnt give any error

**Comment by vibhor1997a** [comment]
What OS and version of package are you using? The following works fine for me for version `2.1.2` on `Windows 7`.

```javascript
const { c } = require('compile-run');
c.runSource('#include<stdio.h>\nint main(){printf("Hello world");return 0;}', { stdin: '10\n20}' }).then(r => console.log(r)).catch(err => console.log(err));
```

Output:
```shell
{ stderr: '', stdout: 'Hello world', exitCode: 0 }
```

**Comment by Rex1911** [comment]
Im coding in [Cloud9,](https://c9.io) which I believe runs on `Ubuntu 14`. Also the package version is `2.1.2`. I forgot to mention that 6-7 out of 10 tries show this error, so you probably didn't encounter the error on that single try. Also, I run the same code with different inputs 2-4 times in very quick successions. Is this causing the issue?

**Comment by vibhor1997a** [comment]
I think its happening as the `stdin` stream is closed before we're writing input to it. I'll update you with the fix.

**Comment by vibhor1997a** [comment]
Hello,
Please check the version `2.1.3`. I made some fixes and please let me know if the issue still exist.

**Comment by vibhor1997a** [comment]
I am closing this. If you are still facing the same issue in the newer version. Please comment so I would reopen it.

**Comment by mav-raj** [comment]
This issue still persist, if you try run multiple testcases in a loop.

**Comment by vibhor1997a** [comment]
Hi @mav-raj 
Can you please provide a detailed scenario where it fails and gives this error?

**Comment by mav-raj** [comment]
hi @vibhor1997a ,
Sorry for late response, it is not related with multiple case, this error is shown in c and cpp, if you are compiling with some input/s and have not use either of input or output, For eg, 
"#include<stdio.h>
int main() {
    return 0;
}"
try compiling this code with input "2\n2" in both c and cpp.
