### ISSUE TITLE
Hardcoding \n in Stdin

### ISSUE THREAD

**Issue by shanmuksai** [vibhor1997a/compile-run#4]
hi,
When in am looking into your java support source code you had appended **\n** to stdin. What is the necessity of appending **\n** to stdin!! What happens when we remove **\n** .

**Comment by vibhor1997a** [comment]
It is just for leaving a line blank after the input.

**Comment by shanmuksai** [comment]
> It is just for leaving a line blank after the input.

what happens when we remove that **\n**

**Comment by vibhor1997a** [comment]
I believe it should work as expected. Its just personal preference of myself to leave an empty line.

**Comment by shanmuksai** [comment]
Thanks a lot,
