### ISSUE TITLE
throwing an error while compiling a c and c++programs

### ISSUE THREAD

**Issue by harikabezawada** [vibhor1997a/compile-run#4]
I am trying to compile a C/C++ code,but I am getting a event error
Error: spawn gcc ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:240:19)
    at onErrorNT (internal/child_process.js:415:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)

**Comment by vibhor1997a** [comment]
Is gcc compiler installed on your machine?

**Comment by harikabezawada** [comment]
No, Mine is windows 10 Machine , is it possible to install a gcc compiler in windows ?.if so, it would be helpful if you provide me any ref for installing it in windows 10 as In most of the link I could able to find with linux/Mac .

**Comment by harikabezawada** [comment]
I have Installed gcc compiler in my system .Its working . Thank you
