### ISSUE TITLE
Run program with user input

### ISSUE THREAD

**Issue by shiva9610** [vibhor1997a/compile-run#5]
If i want to give some user input, how can i do this by your package. Please help on it.

Attached Screenshot.

Thanks
![error](https://user-images.githubusercontent.com/20677368/61364215-02b40a80-a8a3-11e9-808d-7f9b42fdfb73.jpg)

**Comment by vibhor1997a** [comment]
You can use the stdin option like the following to pass the input: 

    let cp = require('compile-run');
    cp.python.runSource(`inp = input("What is your name?\\n")\nprint(inp)`, {
        stdin: "vibhor"
    }, (err, res) => {
        console.log(err, res);
    });

It takes all of the input at once, submits to your program and collects all the output and gives you back.
 
Interactive user Input/Output is not supported currently what I think you want to achieve. Feels like a good idea to work upon. I will work upon it soon.
