### ISSUE TITLE
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type object

### ISSUE THREAD

**Issue by mav-raj** [vibhor1997a/compile-run#6]
Getting this path issue while compiling java code. Tried on Ubuntu 18.04 and Mint 19.1 with java installed.

**Comment by vibhor1997a** [comment]
Can you post the whole error with the call stack?

**Comment by mav-raj** [comment]
Trace
    at java.runSource.then.result (/[local-path]/server.js:71:19)
    at process._tickCallback (internal/process/next_tick.js:68:7)
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type object
    at validateString (internal/validators.js:125:11)
    at Object.dirname (path.js:1260:5)
    at /[local-path]/node_modules/compile-run/dist/lib/java/run-source.js:67:48
    at step (/[local-path]/node_modules/compile-run/dist/lib/java/run-source.js:32:23)
    at Object.next (/[local-path]/node_modules/compile-run/dist/lib/java/run-source.js:13:53)
    at fulfilled (/[local-path]/node_modules/compile-run/dist/lib/java/run-source.js:4:58)
    at process._tickCallback (internal/process/next_tick.js:68:7

**Comment by vibhor1997a** [comment]
Can you please demonstrate how you're calling the `java.runSource` function? As I checked at my end and try to recreate the issue and got no issue.

**Comment by mav-raj** [comment]
app.post("/compiler/compile", (req, res) => {
  const body = req.body;
  // console.log(body);
  const lang = body.lang;
  const code = body.code;
  let input = body.input;
  input = input.trim();
  let len = input.length;
  switch (lang) {
    case "c":
      c.runSource(code, len > 0 ? { stdin: input } : null)
        .then(result => {
          // console.log(result);
          res.status(200).json(result);
        })
        .catch(err => {
          res.send(err);
        });
      break;
    case "java":
      java
        .runSource(code, len > 0 ? { stdin: input } : null)
        .then(result => {
          console.log(result);
          res.status(200).json(result);
        })
        .catch(err => {
          res.send(err);
        });
      break;
    default:
      result = compileC(code, input);
  }
});

**Comment by vibhor1997a** [comment]
I think the library is not able to setup the temporary directory where it stores the source files. What platform/OS are you using? Which version of compile-run you're using?

**Comment by mav-raj** [comment]
OS is Ubuntu 18.04 and version of compile run is 2.3.2

**Comment by mav-raj** [comment]
> I think the library is not able to setup the temporary directory where it stores the source files. What platform/OS are you using? Which version of compile-run you're using?

I checked in home/.compile-run2/temp, contains 5 folders, but I found something unusual in java folder, as every other folder contains file.c/cpp/js/py in their respective folders but in java the file extension was not present and seperate folders have been created namely source-someAlphaNumericRandomString. Thought this will be helpful solving the issue.

**Comment by vibhor1997a** [comment]
In java we save in this way a folder of random name in java folder. Inside randomly named folder there are 2 files .class and .java

**Comment by vibhor1997a** [comment]
Are you able to run for other languages or they also give the same error?

**Comment by mav-raj** [comment]
> In java we save in this way a folder of random name in java folder. Inside randomly named folder there are 2 files .class and .java

No, all folders are empty. No .class and and .java files at all.

**Comment by mav-raj** [comment]
> Are you able to run for other languages or they also give the same error?

Yeah, issue persist only when I compile java code. others are working fine.

**Comment by vibhor1997a** [comment]
I think its some permissions issue. I will check this out on an ubuntu machine. Meanwhile if you can try deleting the whole .compile-run2 directory and try again.

You can also try giving yourself all permissions for the directory by 
`sudo chmod 777 <compile-run2 directory path> -R`.

**Comment by mav-raj** [comment]
> Can you please demonstrate how you're calling the `java.runSource` function? As I checked at my end and try to recreate the issue and got no issue.

Can you just provide me a sample boilerplate code which compiles successfully on your side. I think may be I am missing something.
Also i changed the permission like you said but still no luck.

**Comment by vibhor1997a** [comment]
let { java } = require('compile-run');

    let code = `public class TestingCompileRun {
        public static void main(String[] args) {
            System.out.println("Hello World");
        }
    }`;

    let input = '2\n';
    let len = 1;

    java
        .runSource(code, len > 0 ? { stdin: input } : null)
        .then(res => console.log(res))
        .catch(err => console.log(err));

This is what I tried I used your code and tried different values for len and input but it ran on my maching. I am running it on windows 10. I will test it on my mac(maybe it will also have issue as its also unix) and try to check it out on ubuntu.

**Comment by vibhor1997a** [comment]
The same runs on my mac too.

**Comment by mav-raj** [comment]
> The same runs on my mac too.

Yeah please try on Ubuntu like Unix. I am updating this issue as I've tried on Ubuntu 18.04 and Mint 19.1.

**Comment by vibhor1997a** [comment]
I tested the above code on my ubuntu 18.04 instance and it worked fine.

![screenshot1](https://user-images.githubusercontent.com/29769218/67751274-ce7de780-fa56-11e9-8fa8-88078e7b533e.png)

**Comment by mav-raj** [comment]
> I tested the above code on my ubuntu 18.04 instance and it worked fine.
> 
> ![screenshot1](https://user-images.githubusercontent.com/29769218/67751274-ce7de780-fa56-11e9-8fa8-88078e7b533e.png)

Seems not working for me. I have java-11-openjdk-amd64 on both of my machine.

**Comment by vibhor1997a** [comment]
Can you please try the above code I tried for java by running it seperately and without express js(which I suppose you're using)?

**Comment by mav-raj** [comment]
> Can you please try the above code I tried for java by running it seperately and without express js(which I suppose you're using)?

I tried and it returned the same result as yours.
 { stderr: '',
  stdout: 'Hello World\n',
  exitCode: 0,
  memoryUsage: 233472,
  cpuUsage: 10420 }
But the question is why only for java and not others. Even if I am using express js.

**Comment by vibhor1997a** [comment]
I think the problem is how you're running it. I believe you're using `pm2` or `forever` like something to run it. I think the issue is due to permissions. Its not able to create the files where it needs to due to lack of permissions. Also you said the folders were empty. I will test this out on express with an ubuntu machine and try to recreate the issue.

**Comment by mav-raj** [comment]
> I think the problem is how you're running it. I believe you're using `pm2` or `forever` like something to run it. I think the issue is due to permissions. Its not able to create the files where it needs to due to lack of permissions. Also you said the folders were empty. I will test this out on express with an ubuntu machine and try to recreate the issue.

Hey I think i figured it out...In my boilerplate code, the main class was not public, I changed it to public and then it compiled successfully.
Previously it was like this
`class Main {
public static void main(String args []) {
// code
}
}`

Changed it to:
`public class Main {
public static void main(String args []) {
// code
}
}`
