### ISSUE TITLE
secure way to accept user input

### ISSUE THREAD

**Issue by elnur0000** [vibhor1997a/compile-run#8]
Hi,
I am creating a competitive programming platform and wondering how secure is this module in terms of user input, are there any precautions for harmful code or stdin ? if not, do you have any tips for sanitizing the input or just getting rid of this problem in any other way ?  
might even push it here, if any success...

**Comment by vibhor1997a** [comment]
Hey @norzalovi,
This module doesn't offer security for running user code. You should run the code in a containerized environment with or without this module to prevent malicious activity due to the user input.
